### ISSUE TITLE
Общие классы над метаданными

### ISSUE THREAD

**Issue by otymko** [1c-syntax/mdclasses#1]
Реализовать общий класс над метаданными конфигурации (в дальнейшем EDT), в котором будет доступно:
* Режим совместимости
* Основной язык
* Тип модуля: МодульМенеджера, МодульОбъекта, МодульФормы, МодульНабораЗаписей и т.п.

**Comment by nixel2007** [comment]
Кажется, это несколько классов.
Обёртка над корнем конфигурации, обёртка над свойствами-перечислениями корня конфигурации.
Для типов модулей вообще не все так прозрачно :)

**Comment by asosnoviy** [comment]
Общий модуль,
Модулей объекта, 
Модуль менеджера,
Модуль формы,
Модулей команды

**Comment by otymko** [comment]
@DoublesunRUS
"Ну то есть один класс будет реализовывать абстрактные методы обращения к метаданным и при создании провайдера диагностик я должен буду передать его в качестве параметра.
Для EDT я напишу свой провайдер метаданных, который будет возвращать метаданные через нативные методы EDT. А для LS будет свой провайдер, который будет строить дерево метаданных как он сам хочет."

**Comment by nixel2007** [comment]
Тоже оставлю для истории:

Nikita Gryzlov, [14.07.19 14:56]
я тут немного поразмыслил на тему провайдера. хочу понять, как это будет работать на уровне прикладного кода.

отталкиваемся от изначальной задачи. дерево метаданных нужно в конкретных диагностиках. допустим в ServerContext будет некий метод, который вернет данные о корне конфигурации.

допустим эти данные о корне лежат даже в виде какого-то интерфейса, который предоставляется либой mdClasses. эта же либа предоставляет дефолтную реализацию этого интерфейса.
у этого интерфейса IConfiguration будет метод getScriptVariant, который вернет вариант языка.

допустим даже, что мы отказывается от Enum'ов в дереве конфигурации и работаем со строками/числами/прочими примитивами. хреновый вариант, но ради упрощения ок.

ок, есть интерфейс, есть метод. в mdClasses есть высокоуровневый адаптер, который умеет этот интерфейс реализовывать.
усложняем задачу - берем форму. у нее есть коллекция обработчиков, реквизитов, элементов, команд. у команд есть куча свойств.

оооокей, все это добро завернули в интерфейсы. ынтырпрайз во всю душу.

теперь мы встраиваем BSL LS в EDT. @Doublesun хочет прокинуть туда данные дерева из EDT, чтобы два раза не парсить XML. но диагностики ничего не знают про модель ЕДТ, они ждут набор интерфейсов из mdClasses.
значит, нужно писать враппер ВСЕГО дерева конфигурации из модели EDT в модель mdClasses. со всей сотней, а то и тысячей (в долгосрочной перспективе) интерфейсов.

я правильно понимаю?

Мне Сашу жалко, если честно.

Nikita Gryzlov, [14.07.19 14:58]
и я бы подождал пару минуток на сборку проекта, но второй раз бы распарсил XML...

Nikita Gryzlov, [14.07.19 15:00]
тут получается огромный пласт работы как со стороны mdClasses, так и со стороны плагина в EDT. профит понятен, но затраты кажутся чрезмерными, если честно. работа через интерфейсы и прочая Effective Java по Блоху - это конечно очень круто и хорошо. но кажется, что это несколько не наш уровень прикладного использования и свободных сил

Александр Капралов, [14.07.19 15:05]
[В ответ на Nikita Gryzlov]
Ну наверное можно при старте плагина 1 раз распарсить, а потом только прокидывать в него информацию об объектах которые можно перепарсить.

Nikita Gryzlov, [14.07.19 15:05]
[В ответ на Александр Капралов]
да, я тоже об этом думаю. надо только на стороне EDT тогда какой-то watcher за MDO файлами навесить.

Nikita Gryzlov, [14.07.19 15:06]
и дергать метод из какого-нибудь ServerContext

**Comment by theshadowco** [comment]
Наверное оно #33
