### ISSUE TITLE
Форма. Состав элементов

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/mdclasses#111]
Реализовать чтение информации из описания формы
 - элементы (древовидная и плоская модель), включая их типы и свойства
 - команды
 - обработчики (часть контекста)
 - динамические списки (с запросами, которые как-то надо будет отдать в BSLLS)

**Comment by theshadowco** [comment]
@nixel2007

**Comment by otymko** [comment]
Хороший приме для разбора форм в двух форматах: УправляемаяКонсольОтчетов 3.8.8\Forms\Основная.xml. Но ее можно будет включить в ресурсы только с разрешения автора. Либо найти что-то аналогично "вкусное".

**Comment by otymko** [comment]
Подробный состав что есть на упр. формах в xsd схеме -> https://github.com/1c-syntax/mdclasses/blob/f5a0c4aa04117d1d7543c595cf69548346131266/src/main/resources/xsd/original/ManagedApplicationLogForm.xsd
