### ISSUE TITLE
Описание моделей объектов с использованием аннотаций

### ISSUE THREAD

**Issue by alkoleft** [1c-syntax/mdclasses#130]
Большая часть XML в формате конфигуратора и EDT имеют схожую структуру, отличающуюся только тем что элементы в формате конфигуратор расположены в "группах"

Такой формат описания позволит читать объекты промежуточных объектов, а также выполнять запись
```java
  @XStreamAlias("Name")
  @Group("Properties")
  String name;

  @XStreamAlias("Synonym")
  @Group("Properties")
  MultiLangString synonym;
```

**Comment by otymko** [comment]
@theshadowco пока закрываем задачу
