### ISSUE TITLE
Разделение настроек для форматов EDT и конфигуратора

### ISSUE THREAD

**Issue by alkoleft** [1c-syntax/mdclasses#133]
Хочется иметь возможность разделить настройки XStream для конфигуратора и для EDT
Причины:
1. Возможность писать установив корректные алиасы
2. За счет различных настроек можно переложить часть логики разбора на XStream
Например настройка для конфигуратора
```java
    xStream.aliasField("RegisterRecords", Document.class, "registerRecords");
    xStream.aliasType("xr:Item", Either.class);
```
позволит избавится от обертки `DesignerXRItems`.
Но она конфликтует с настройкой для EDT
```java
    xStream.addImplicitArray(Document.class, "registerRecords", Either.class);
```

**Comment by theshadowco** [comment]
По сути - надо выделить два парсера, для каждого из форматов, а верхом - текущую либу без привязки к формату

**Comment by theshadowco** [comment]
и тогда можно будет финализировать классы и упростить сборку...

**Comment by theshadowco** [comment]
@otymko что скажешь?

**Comment by nixel2007** [comment]
не так ли выглядела первая итерация mdclasses, от которой вы ушли на универсальный анмаршаллер? :)

**Comment by theshadowco** [comment]
Ты не понимаешь, это другое )

**Comment by otymko** [comment]
Уже реализовано в рамках релиза 0.9
