### ISSUE TITLE
Поддержка модулей перерасчетов регистра расчетов

### ISSUE THREAD

**Issue by yukon39** [1c-syntax/mdclasses#234]
## Версия
mdclasses: 0.9.2

## Описание ошибки
При чтении списка модулей конфигурации в список модулей не попадает модуль набора записей перерасчета регистра расчетов (РегистрыРасчета.Регистр1.Перерасчеты.Перерасчет1.МодульНабораЗаписей)

## Дополнительно
Ошибка получена при получении данных покрытия конфигурации в проекте Coverage41C (v2.5.1):
`Coverage41C.bat convert --projectDir="tests/testdata" -s src\cf\xml -o linesToCover.xml -c dummy.xml`

В отчет не попадают строки покрытия для модуля [`src/cf/xml/CalculationRegisters/РегистрРасчета1/Recalculations/Перерасчет1/Ext/RecordSetModule.bsl` ](https://github.com/yukon39/coverage-cli/blob/master/tests/testdata/src/cf/xml/CalculationRegisters/%D0%A0%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%A0%D0%B0%D1%81%D1%87%D0%B5%D1%82%D0%B01/Recalculations/%D0%9F%D0%B5%D1%80%D0%B5%D1%80%D0%B0%D1%81%D1%87%D0%B5%D1%821/Ext/RecordSetModule.bsl)

**Comment by asosnoviy** [comment]
Кажется опять пропал
