### ISSUE TITLE
[NEW] Добавить поле languageTag для перечисления ScriptVariant

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/mdclasses#248]
## Описание функциональности

Сейчас для получения локали (Locale) по варианту встроенного языка приходится заниматься конвертированием English->en и Russian->ru. Было бы здорово добавить геттер с языковым тэгом сразу в ScriptVariant#getLanguageTag

**Comment by theshadowco** [comment]
есть shortName

![image](https://user-images.githubusercontent.com/9591731/221633451-3d4a8b3c-4099-4606-aecc-1f8a83e6ef37.png)
