### ISSUE TITLE
[BUG] Configuration.mdo - it's broken после обновления на версию плагина 1.14.0 (платформа 8.3.24)

### ISSUE THREAD

**Issue by pzhgulev** [1c-syntax/mdclasses#459]
## Версия
плагин 1.14.0

## Описание ошибки
ERROR: Can't read file 'C:\FirstBIT\GitlabRunner\builds\s_jVzFWF\0\firstbit_1c\firstbit_erp\FirstBITERP\src\Configuration\Configuration.mdo' - it's broken 
: 

## Дополнительная информация
лог https://pastebin.com/0q5u2Fib
через ГК конфа перегоняется в формат EDT и на этом репо делается прогон
платформа 8.3.24.1467 без режима совместимости. 
EDT 2023.3.2 

[Configuration mdo.zip](https://github.com/user-attachments/files/15807679/Configuration.mdo.zip)

**Comment by theshadowco** [comment]
Баг из-за английской локали и моего костыля :(
