### ISSUE TITLE
Не определяется поддержка для Планов обмена

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/mdclasses#59]

**Comment by asosnoviy** [comment]
Это может быть вранье, пруфов нет

**Comment by otymko** [comment]
@asosnoviy вроде работает.
![image](https://user-images.githubusercontent.com/11651847/82574550-7ef93780-9bb1-11ea-8b9d-9343bf5dd690.png)

**Comment by theshadowco** [comment]
Вроде работает (на моей конфе отработало). так что, когда подтвердится - создадим новый
