### ISSUE TITLE
Состав общего реквизита и общий реквизит в объектах

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/mdclasses#94]
1. Реализовать чтение состава общего реквизита
2. Создать перечисление ВидРеквизита (Пользовательский, Общий, Стандартный)
3. Для всех реквизитов, прочитанных из метаданных указать тип - пользовательский
4. Для всех объектов из состава общего реквизита добавить его как общий реквизит

**Comment by alkoleft** [comment]
Запишите на меня пожалуйста
